# Edit this configuration to match your system. Currently every one of
# these but LD is used directly, but you might as well be complete.

DREAM_CFLAGS= -Os --fast-math -fomit-frame-pointer -ml -m4-single-only -ffunction-sections -fdata-sections -D_arch_dreamcast -D_arch_sub_pristine -Wall -s  -fno-stack-protector -fno-strict-aliasing -ffreestanding
#-O2 --fast-math
DREAM_LDFLAGS=-ml -m4-single-only -Wl,-Ttext=0x8c00b800 -nostartfiles -nostdlib 
DREAM_LIBS=-Wl,--start-group  -Wl,--end-group -Wl,--gc-sections
#-Wl,--gc-sections -Tshlelf.xc -Wl,-Tshlelf.xc 
TARGET=sh-elf
DCBASE=/opt/toolchains/dc/$(TARGET)
CC=sh-elf-gcc #=sh-elf-gcc -ml -O2 -m4-single-only -Wall  -Xlinker 
LD=$(KOS_LD)
AS=$(KOS_AS)
AR=$(KOS_AR)
OBJCOPY=$(KOS_OBJCOPY)


