/*  maketmpl.c

DESCRIPTION

    Combines three files (template, bootstrap 1, bootstrap 2) into a single
    new IP.BIN template.

*/
#include <string.h>
#include <stdlib.h>
#include <stdio.h>

#include "boot1.h"

union
{
    unsigned int integer;
    unsigned char byte[4];
} tempInt;

int main (int argc, char **argv)
{
    FILE *ip, *binary, *ip_out;
    char ip_buf[0x8000];
    int file_size;

    if (argc != 4)
    {
        fprintf (stderr, "Usage: %s (IP.BIN Original) (1ST_READ.BIN) (Hacked IP.BIN)\n", argv[0]);
        exit (1);
    }

    memset (ip_buf, 0, sizeof (ip_buf));    

    ip = fopen (argv[1], "rb");
    binary = fopen(argv[2], "r");
	ip_out= fopen(argv[3], "wb");
	
   if(binary==NULL) {
      fprintf(stderr,"%s not found!\n",argv[2]);
	  exit(1);
   } else {
      fseek(binary,0L,SEEK_END);
      tempInt.integer=ftell(binary);
      fclose(binary);
   }
    
    if (!ip)
        fprintf (stderr, "Unable to open '%s'.\n", argv[1]);
    else if (!fread (ip_buf, sizeof (ip_buf), 1, ip))
        fprintf (stderr, "Unable to read Original IP.BIN\n");
    else { 
		memcpy(ip_buf+0x3800,boot1,sizeof(boot1));
		//offset given in the MAPfile generated by gcc
		int data_size_OFFSET = 0x8c00d454;
		((int*)ip_buf)[((data_size_OFFSET-0x8c00b800)+0x3800)/4] = tempInt.integer;
		
		//patch region free
		ip_buf[0x30] = 'J';
		ip_buf[0x31] = 'U';
		ip_buf[0x32] = 'E';
		
		//patch VGA
		ip_buf[0x3D] = '1';
		
		//region free part2
		unsigned char rawData[75] =
		{
			0x46, 0x6F, 0x72, 0x20, 0x4A, 0x41, 0x50, 0x41, 0x4E, 0x2C, 0x54, 0x41, 0x49, 0x57, 0x41, 0x4E, 
			0x2C, 0x50, 0x48, 0x49, 0x4C, 0x49, 0x50, 0x49, 0x4E, 0x45, 0x53, 0x2E, 0x0E, 0xA0, 0x09, 0x00, 
			0x46, 0x6F, 0x72, 0x20, 0x55, 0x53, 0x41, 0x20, 0x61, 0x6E, 0x64, 0x20, 0x43, 0x41, 0x4E, 0x41, 
			0x44, 0x41, 0x2E, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x0E, 0xA0, 0x09, 0x00, 
			0x46, 0x6F, 0x72, 0x20, 0x45, 0x55, 0x52, 0x4F, 0x50, 0x45, 0x2E, 
		} ;
		
		int i;
		for(i=0;i<75;i++){
			ip_buf[0x3704+i] = rawData[i];
		}

		
		fwrite (ip_buf, sizeof (ip_buf),1,ip_out);
		fclose(ip_out);
	}

    fprintf (stderr, "Done!\n");
	return 0;
}
